/**
 * build-us-geo.ts — bakes US state outlines into a server-only TS module.
 *
 * Reads `us-atlas/states-albers-10m.json` (already projected to the standard
 * 975×610 Albers USA grid) and emits `lib/us-states-geo.ts` with one entry
 * per state: { code, name, d }.
 *
 * Why bake at build time:
 *   - Zero runtime dep on us-atlas / topojson-client / d3-geo.
 *   - SVG paths are imported only from server components, so the strings
 *     never ship to the client either — the choropleth renders as static
 *     SVG markup, like Sparkline + MiniBar.
 *
 * Run when state boundaries change (effectively never): `tsx
 * apps/analytics-web/scripts/build-us-geo.ts`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { feature } from 'topojson-client';
import { geoPath } from 'd3-geo';
import type {
  FeatureCollection,
  Feature,
  Geometry,
  GeoJsonProperties,
} from 'geojson';

// FIPS state codes → 2-letter USPS postal codes. 50 states + DC + PR.
// (PR is in us-atlas county data but not the states layer; harmless to keep.)
const FIPS_TO_CODE: Record<string, string> = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA',
  '08': 'CO', '09': 'CT', '10': 'DE', '11': 'DC', '12': 'FL',
  '13': 'GA', '15': 'HI', '16': 'ID', '17': 'IL', '18': 'IN',
  '19': 'IA', '20': 'KS', '21': 'KY', '22': 'LA', '23': 'ME',
  '24': 'MD', '25': 'MA', '26': 'MI', '27': 'MN', '28': 'MS',
  '29': 'MO', '30': 'MT', '31': 'NE', '32': 'NV', '33': 'NH',
  '34': 'NJ', '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND',
  '39': 'OH', '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI',
  '45': 'SC', '46': 'SD', '47': 'TN', '48': 'TX', '49': 'UT',
  '50': 'VT', '51': 'VA', '53': 'WA', '54': 'WV', '55': 'WI',
  '56': 'WY', '72': 'PR',
};

interface StateProps extends GeoJsonProperties {
  name: string;
}

const TOPO_PATH = resolve(
  process.cwd(),
  'apps/analytics-web/node_modules/us-atlas/states-albers-10m.json',
);
const OUT_PATH = resolve(
  process.cwd(),
  'apps/analytics-web/lib/us-states-geo.ts',
);

const topology = JSON.parse(readFileSync(TOPO_PATH, 'utf8'));
const states = feature(topology, topology.objects.states) as unknown as
  FeatureCollection<Geometry, StateProps>;

// Albers USA grid is already in pixel space; an identity projection is all
// we need. geoPath returns the d-string with default precision.
const path = geoPath();

// Hand-tuned label-anchor offsets for tiny northeastern states that get
// covered by their neighbours when the label sits inside the polygon. The
// callout target stays at the centroid; the label itself is rendered to
// the right and connected with a thin leader line.
const CALLOUT: Record<string, { dx: number; dy: number }> = {
  CT: { dx: 60, dy: 14 },
  RI: { dx: 60, dy: 30 },
  MA: { dx: 60, dy: -2 },
  NJ: { dx: 50, dy: 20 },
  DE: { dx: 50, dy: 8 },
  MD: { dx: 50, dy: 22 },
  DC: { dx: 50, dy: 36 },
  NH: { dx: 60, dy: -18 },
  VT: { dx: -60, dy: -10 },
};

const rows = states.features
  .map((f: Feature<Geometry, StateProps>) => {
    const fips = String(f.id ?? '').padStart(2, '0');
    const code = FIPS_TO_CODE[fips];
    if (!code) {
      console.warn(`skipping unknown FIPS ${fips} (${f.properties?.name ?? '?'})`);
      return null;
    }
    const d = path(f);
    if (!d) {
      console.warn(`empty geometry for ${code}`);
      return null;
    }
    const [cx, cy] = path.centroid(f);
    const callout = CALLOUT[code] ?? null;
    return {
      code,
      name: f.properties.name,
      d,
      cx: Number(cx.toFixed(1)),
      cy: Number(cy.toFixed(1)),
      callout,
    };
  })
  .filter(
    (r): r is {
      code: string; name: string; d: string;
      cx: number; cy: number;
      callout: { dx: number; dy: number } | null;
    } => r !== null,
  )
  .sort((a, b) => a.code.localeCompare(b.code));

const bbox = topology.bbox as [number, number, number, number];
// us-atlas Albers grid bbox includes Alaska/Hawaii insets that extend left
// of zero; the canonical viewBox is 0 0 975 610.
const VIEW_BOX = '0 0 975 610';

const out = `// AUTO-GENERATED by apps/analytics-web/scripts/build-us-geo.ts. Do not edit.
// Source: us-atlas/states-albers-10m.json (Albers USA, 975×610 pixel grid).

export interface UsStateGeo {
  readonly code: string;
  readonly name: string;
  readonly d: string;
  /** Albers-pixel centroid — where to anchor the label or hover effect. */
  readonly cx: number;
  readonly cy: number;
  /**
   * Optional leader-line callout for tiny states (CT, RI, NJ, DE, MD, DC,
   * NH, VT, MA). When present, render the label at (cx + dx, cy + dy) and
   * draw a thin line from the centroid to the label.
   */
  readonly callout: { dx: number; dy: number } | null;
}

export const US_STATES_GEO: readonly UsStateGeo[] = ${JSON.stringify(rows, null, 2)} as const;

export const US_VIEW_BOX = '${VIEW_BOX}' as const;
export const US_BBOX = ${JSON.stringify(bbox)} as const;
`;

writeFileSync(OUT_PATH, out);

const total = out.length;
console.log(`Wrote ${rows.length} states → ${OUT_PATH} (${(total / 1024).toFixed(1)} kB)`);
